"""empty message

Revision ID: 587df64e0545
Revises: 2c20beac00d0
Create Date: 2024-07-17 12:04:38.267073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587df64e0545'
down_revision = '2c20beac00d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categories',
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('categories_id', 'posts_id')
    )
    op.drop_table('post_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_categories',
    sa.Column('categories_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('categories_id')
    )
    op.drop_table('posts_categories')
    # ### end Alembic commands ###
