"""empty message

Revision ID: 61145ab5f3f5
Revises: dedaf3e369d5
Create Date: 2024-07-17 11:43:23.957976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61145ab5f3f5'
down_revision = 'dedaf3e369d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tittle')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('activ')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activ', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('active')

    op.drop_table('profile')
    op.drop_table('posts')
    # ### end Alembic commands ###
